default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: react_rails_authentication_app_development

test:
  <<: *default
  database: react_rails_authentication_app_test

production:
  <<: *default
  database: react_rails_authentication_app_production
  username: react_rails_authentication_app
  password: <%= ENV['REACT_RAILS_AUTHENTICATION_APP_DATABASE_PASSWORD'] %>
